### ISSUE TITLE
Hey! 

### ISSUE THREAD

**Issue by michaeldabbott** [HotPotatoC/twitter-clone#11]
I'm currently looking over your repo and it's pretty good. 

In particular I'm looking at how you've organised your module/services, is there any particular reason you decided to opt in the execute pattern for interfaces? 
I've noticed this pattern used when you need easier accessibility for testing, so you only need to mock the single function a handler might need rather than 10 or so to implement the interface

**Comment by HotPotatoC** [comment]
Hi,

Very sorry for the late reply. To be honest, I have completely forgotten how I organized my modules/services 😂. Now that I think about it, I think it's superfluous because there's just one signature.

But hey, now that I have some free time I'm planning on rewriting the project from scratch. Closing this for now.

Thanks for asking
